### ISSUE TITLE
Not working in Node.js

### ISSUE THREAD

**Issue by Jebble** [joaocarmo/vcard-creator#1]
In the documentation it says "With a bundler (e.g. webpack) or in Node.js you can just require / import it."

When this piece of code is copy/pasted into a Node.js project it doesn't work.

```
var VCard = require('vcard-creator');
var myVCard = new VCard();
```
results in `TypeError: VCard is not a constructor`

If I log VCard you see that it is actually an object `{ default: [Getter] }`
So then looking at the window object if you'd include the library as a script I tried `var myVCard = VCard.default` which doesn't throw an error at first but then `myVCard` doesn't have any methods resulting in `TypeError: myVCard.addName is not a function`.

**Comment by joaocarmo** [comment]
@Jebble , You might want to try and import it like this:

```javascript
var VCard = require('vcard-creator').default;
var myVCard = new VCard();
```

Let me know if this still throws an error. I'll either issue a fix or update the documentation. You can also submit a PR!

**Comment by joaocarmo** [comment]
[CLOSING] Updated the docs.
