### ISSUE TITLE
Typescript error Could not find declaration file for module vcard-creator

### ISSUE THREAD

**Issue by Dauliac** [joaocarmo/vcard-creator#11]
Hey
I had the error: 
```
Could not find declaration file for module vcard-creator
```
In the node module the definition file don't have the same name than js library:
- `vcard-creator.js`
- `VCard.d.ts`

A workaround I found is to move `VCard.d.ts` as `vcard-creator.d.ts` but that's not a satisfying  solution.

If someone know how packaging works, help is welcome.

Unfortunately I don't have competencies to fix that.

**Comment by joaocarmo** [comment]
@Dauliac , thank you for submitting this issue.

I've made an update that should fix it, available as `v0.3.1`.

Please, re-open this issue or open a new one if the problem persists after updating.

**Comment by arthurkhlghatyan** [comment]
Hey there,

Still encountering the same issue, have 0.3.3 installed in my project.

Thanks.

**Comment by joaocarmo** [comment]
@arthurkhlghatyan, thank you for reporting this. I believed I had fixed that already. Please try out `v0.3.4` as it should finally solve this issue.
