### ISSUE TITLE
Running into "vcard-creator.d.ts is not a module" when trying to build.

### ISSUE THREAD

**Issue by BeMacized** [joaocarmo/vcard-creator#13]
Hi! I ran into an issue while trying to use your package: 

I installed vcard-creator (v0.3.2) using `yarn add vcard-creator` and imported it like `import VCard from 'vcard-creator';`

However, when I try to build my project I run into the following error:
```
$ tsc
src/<REDACTED>.ts:11:19 - error TS2306: File '/home/<REDACTED>/node_modules/vcard-creator/dist/vcard-creator.d.ts' is not a module.

11 import VCard from 'vcard-creator';
                     ~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
```

Not fully sure if there is an issue with your package, or whether I'm just using it wrong. 

<details>
<summary>My tsconfig.json, in case it is relevant.</summary>

```javascript
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitReturns": false,
        "noUnusedLocals": true,
        "outDir": "lib",
        "sourceMap": true,
        "strict": false,
        "target": "es2017",
        "types": [],
        "experimentalDecorators": true,
        "declaration": true
    },
    "compileOnSave": true,
    "include": ["src"]
}
```
</details>

**Comment by joaocarmo** [comment]
@BeMacized thank you for bringing this to my attention. #14 should fix this issue as of `v0.3.3`.
