### ISSUE TITLE
Bug in addMedia function

### ISSUE THREAD

**Issue by arthurkhlghatyan** [joaocarmo/vcard-creator#15]
[Here](https://github.com/joaocarmo/vcard-creator/blob/4812357e2e7791dd8902f8c5ffaaa57820fd4278/lib/VCard.ts#L224), url variable is not used, instead empty string value is passed to setProperty.

**Comment by joaocarmo** [comment]
@arthurkhlghatyan, there is a PR (#7) to add the missing functionality for `addMedia`. It's been a while now, though.

I'll look into it.
