### ISSUE TITLE
Issue with French phone numbers

### ISSUE THREAD

**Issue by mlbonniec** [joaocarmo/vcard-creator#27]
Hi :)

Thanks for your great module.
However, I've an issue with the phone number.
Phone numbers in France starts with 0. (ex: 0612345678)

The problem is that the `addPhoneNumber` function can only take numbers, and numbers can't start with 0.

Is it possible to change the type to string? Or maybe `number | string`.

Thanks,
Mathis

**Comment by joaocarmo** [comment]
Hi @mlbonniec!

Thank you so much for letting me know about this issue. I believe it affects other countries as well like the UK where something similar is the norm.

It's not a problem if you use the international format, but it is in fact an issue with local numbers that have leading `0`s.

I'll release a new version with this fix.
