### ISSUE TITLE
howto add uid attribute in vcard?

### ISSUE THREAD

**Issue by celevra** [joaocarmo/vcard-creator#32]
Hi,

i need a uid attribute in my vcf files to sync it via carddav:
https://www.evenx.com/vcard-3-0-format-specification
"represents a persistent, globally unique identifier associated with the object"

how can i add it?

regards

Celevra

**Comment by celevra** [comment]
const { 
    v4: uuidv4,
  } = require('uuid');

```
.addURL(uuidv4())
var card = myVCard.toString().replace('URL','UID')
```

is working flawless as a workaround because i'm not using the URL element.

**Comment by joaocarmo** [comment]
@celevra, thank you for submitting an issue! There should be no need for a workaround. I'll be releasing a new version (`v0.5.0`) which will include the `addUID` method to set the `UID`.

**Comment by celevra** [comment]
thank you very much for your work
