### ISSUE TITLE
support es6 modules in browser

### ISSUE THREAD

**Issue by n1ywb** [joaocarmo/vcard-creator#8]

**Comment by joaocarmo** [comment]
Thank you for your suggestion, @n1ywb !

This already works with [skypack](https://www.skypack.dev/). It should go something like the snippet below.

```js
<script type="module">
    import VCard from "https://cdn.skypack.dev/vcard-creator"
</script>
```

I'll make sure to add this to the documentation. Also, feel free to play around with this [codepen](https://codepen.io/joaocarmo/pen/PozdprL).
